name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Set config to...
        2. Run controller with...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste any relevant log output (sanitize tokens!)
      render: shell

  - type: input
    id: version
    attributes:
      label: Zeno Version
      description: Output of `./zeno --version` or release tag
      placeholder: v0.1.0
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: Output of `go version`
      placeholder: go1.21.0

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: Ubuntu 22.04, macOS 14.0, etc.
    validations:
      required: true

  - type: dropdown
    id: provider
    attributes:
      label: Runner Provider
      options:
        - Docker
        - AWS
        - GCP
        - Azure
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
